### ISSUE TITLE
Schema metadata corrupted after restart

### ISSUE THREAD

**Issue by miyachan** [lnx-search/lnx#19] opened 2021-08-30 01:48 UTC
*LNX*: e9804944edc8a7c0af24ee3ba8397b87f1640b5f

I'm trying to figure out how to reproduce this. After the panic I reported in #18, after restarting lnx, I noticed that my index schema that was being returned from the search query was messed up. Searching seems to work as advertised (as in searching `field_a:foo`, will return documents where `foo` is set in `field_a`, but the schema of the search results is messed up).

For example, let's say I have schema where I am only storing 3 fields (`field_a`, `field_b`, `field_c`), but I am indexing 6. before the restart (example)
```sh
$ curl 'http://localhost:4040/indexes/posts/search?query=field_a:foo&mode=normal&limit=50&order_by=-ts'
{"data":{"count":40,"hits":[{"doc":{"field_a":["foo"],"field_b":[4],"field_c":[44]}, # etc
```

Now that same query is returning:

```sh
$ curl 'http://localhost:4040/indexes/posts/search?query=field_a:foo&mode=normal&limit=50&order_by=-ts'
{"data":{"count":40,"hits":[{"doc":{"field_d":["foo"],"field_e":[4],"field_f":[44]}, # etc
```

The _values_ are correct, but the name of the keys are completely different.

However, in trying to reproduce the error, it seems like my lnx install is corrupted. I tried to to create an index like so:

```json
{
    "name": "corrupt",

    "writer_buffer": 144000000,
    "writer_threads": 12,
    "reader_threads": 12,

    "max_concurrency": 24,
    "search_fields": [
        "field_a"
    ],

    "storage_type": "filesystem",
    "set_conjunction_by_default": true,
    "use_fast_fuzzy": false,
    "strip_stop_words": false,

    "fields": {
        "field_a": {
            "type": "text",
            "stored": true
        },
        "field_b": {
           "type": "u64",
           "stored": true,
           "indexed": true,
           "fast": "single"
        },
        "field_c": {
           "type": "u64",
           "stored": true,
           "indexed": true,
           "fast": "single"
        },
        "field_d": {
            "type": "text",
            "stored": false
        },
        "field_e": {
            "type": "text",
            "stored": false
        },
        "field_f": {
            "type": "text",
            "stored": false
        },
        "version": {
            "type": "u64",
            "stored": false,
            "indexed": true,
            "fast": "single"
        }
    },
    "boost_fields": {}
}
```

then index these documents:

```
[
    {"field_a":["foo"], "field_b":[4], "field_c":[44], "field_d":["macbook"], "field_e":["apple"], "field_f":["iphone"], "version":[1]},
    {"field_a":["bar"], "field_b":[5], "field_c":[55], "field_d":["laptop"], "field_e":["micrsoft"], "field_f":["galaxy"], "version":[2]},
    {"field_a":["redbull coke"], "field_b":[6], "field_c":[66], "field_d":["thinkpad"], "field_e":["netflix"], "field_f":["nexus"], "version":[3]},
    {"field_a":["vodka sprite"], "field_b":[7], "field_c":[77], "field_d":["ultrabook"], "field_e":["facebook"], "field_f":["blackberry"], "version":[4]},
    {"field_a":["ginger ale whiskey"], "field_b":[8], "field_c":[88], "field_d":["chomebook"], "field_e":["google"], "field_f":["oneplus"], "version":[5]}
]
```

When I added them I got no error:

```sh
 $ curl -X POST -d@corrupt_data.json -H "Content-Type: application/json" http://localhost:4040/indexes/corrupt/documents?wait=true
{"data":"added documents","status":200}
```

But in the `lnx` logs I saw

```
Aug 30 01:23:56 torako lnx[635823]: [2021-08-30][01:23:56] | engine::index::writer | INFO  - [ WRITER @ corrupt ][ TRANSACTION 0 ] completed operation ADD-DOCUMENT
Aug 30 01:23:56 torako lnx[635823]: [2021-08-30][01:23:56] | engine::index::writer | INFO  - [ WRITER @ corrupt ][ TRANSACTION 1 ] completed operation ADD-DOCUMENT
Aug 30 01:23:56 torako lnx[635823]: [2021-08-30][01:23:56] | engine::index::writer | INFO  - [ WRITER @ corrupt ][ TRANSACTION 2 ] completed operation ADD-DOCUMENT
Aug 30 01:23:56 torako lnx[635823]: [2021-08-30][01:23:56] | engine::index::writer | INFO  - [ WRITER @ corrupt ][ TRANSACTION 3 ] completed operation ADD-DOCUMENT
Aug 30 01:23:56 torako lnx[635823]: [2021-08-30][01:23:56] | engine::index::writer | INFO  - [ WRITER @ corrupt ][ TRANSACTION 4 ] completed operation ADD-DOCUMENT
Aug 30 01:23:56 torako lnx[635823]: thread 'thrd-tantivy-index3' panicked at 'Expected a u64/i64/f64 field, got Str("redbull coke") ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.16.0/src/fastfield/mod.rs:208:14
Aug 30 01:23:56 torako lnx[635823]: stack backtrace:
Aug 30 01:23:56 torako lnx[635823]:    0: rust_begin_unwind
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
Aug 30 01:23:56 torako lnx[635823]:    1: std::panicking::begin_panic_fmt
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
Aug 30 01:23:56 torako lnx[635823]:    2: tantivy::indexer::index_writer::index_documents
Aug 30 01:23:56 torako lnx[635823]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 30 01:23:56 torako lnx[635823]: thread 'thrd-tantivy-index0' panicked at 'Expected a u64/i64/f64 field, got Str("foo") ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.16.0/src/fastfield/mod.rs:208:14
Aug 30 01:23:56 torako lnx[635823]: stack backtrace:
Aug 30 01:23:56 torako lnx[635823]:    0: rust_begin_unwind
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
Aug 30 01:23:56 torako lnx[635823]:    1: std::thread 'panickingthrd-tantivy-index1::' panicked at 'begin_panic_fmtExpected a u64/i64/f64 field, got Str("bar")
Aug 30 01:23:56 torako lnx[635823]: ',              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.16.0/src/fastfield/mod.rs/rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs::208457::145
Aug 30 01:23:56 torako lnx[635823]:    2: tantivy::indexer::index_writer::index_documents
Aug 30 01:23:56 torako lnx[635823]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 30 01:23:56 torako lnx[635823]: stack backtrace:
Aug 30 01:23:56 torako lnx[635823]:    0: rust_begin_unwind
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
Aug 30 01:23:56 torako lnx[635823]:    1: std::panicking::begin_panic_fmt
Aug 30 01:23:56 torako lnx[635823]:              at thread '/rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rsthrd-tantivy-index4:' panicked at '457Expected a u64/i64/f64 field, got Str("vodka sprite") :', 5/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.16.0/src/fastfield/mod.rs
Aug 30 01:23:56 torako lnx[635823]: :208: 14
Aug 30 01:23:56 torako lnx[635823]: 2: tantivy::indexer::index_writer::index_documents
Aug 30 01:23:56 torako lnx[635823]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 30 01:23:56 torako lnx[635823]: stack backtrace:
Aug 30 01:23:56 torako lnx[635823]: thread 'thrd-tantivy-index2' panicked at 'Expected a u64/i64/f64 field, got Str("ginger ale whiskey") ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.16.0/src/fastfield/mod.rs:208: 14
Aug 30 01:23:56 torako lnx[635823]:  0: rust_begin_unwind
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
Aug 30 01:23:56 torako lnx[635823]:    1: std::panicking::begin_panic_fmt
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
Aug 30 01:23:56 torako lnx[635823]:    2: tantivy::indexer::index_writer::index_documents
Aug 30 01:23:56 torako lnx[635823]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aug 30 01:23:56 torako lnx[635823]: stack backtrace:
Aug 30 01:23:56 torako lnx[635823]:    0: rust_begin_unwind
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
Aug 30 01:23:56 torako lnx[635823]:    1: std::panicking::begin_panic_fmt
Aug 30 01:23:56 torako lnx[635823]:              at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:457:5
Aug 30 01:23:56 torako lnx[635823]:    2: tantivy::indexer::index_writer::index_documents
Aug 30 01:23:56 torako lnx[635823]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm not sure if these two errors are related, but it seems `lnx`'s understanding of the fields and `tanvity`'s aren't in sync.

**Comment by miyachan** [comment] 2021-08-30 02:22
Ok I was able to reproduce the issue - I think the above issue may or may not be related:

```sh
$ cat corrupt.json 
{
    "name": "corrupt",

    "writer_buffer": 144000000,
    "writer_threads": 1,
    "reader_threads": 1,

    "max_concurrency": 24,
    "search_fields": [
        "field_a"
    ],

    "storage_type": "filesystem",
    "set_conjunction_by_default": true,
    "use_fast_fuzzy": false,
    "strip_stop_words": false,

    "fields": {
        "field_a": {
            "type": "text",
            "stored": true
        },
        "field_b": {
           "type": "u64",
           "stored": true,
           "indexed": true,
           "fast": "single"
        },
        "field_c": {
           "type": "u64",
           "stored": true,
           "indexed": true,
           "fast": "single"
        },
        "field_d": {
            "type": "text",
            "stored": false
        },
        "field_e": {
            "type": "text",
            "stored": false
        },
        "field_f": {
            "type": "text",
            "stored": false
        },
        "version": {
            "type": "u64",
            "stored": false,
            "indexed": true,
            "fast": "single"
        }
    },
    "boost_fields": {}
}
$ curl -X POST -d@corrupt.json -H "Content-Type: application/json" http://127.0.0.1:4040/indexes
{"data":"index created","status":200}
$ curl -X POST 'http://localhost:4040/indexes/corrupt/commit'
{"data":"changes committed","status":200}
$ curl 'http://localhost:4040/indexes/corrupt/search?query=*&mode=normal&limit=50&order_by=-version'
{"data":{"count":5,"hits":[{"doc":{"field_a":["foo"],"field_b":[4],"field_c":[44]},"document_id":"10440502902603821756","ratio":1.0},{"doc":{"field_a":["bar"],"field_b":[5],"field_c":[55]},"document_id":"17208387925352628110","ratio":1.0},{"doc":{"field_a":["redbull coke"],"field_b":[6],"field_c":[66]},"document_id":"14689755527796750658","ratio":1.0},{"doc":{"field_a":["vodka sprite"],"field_b":[7],"field_c":[77]},"document_id":"16589393346468196154","ratio":1.0},{"doc":{"field_a":["ginger ale whiskey"],"field_b":[8],"field_c":[88]},"document_id":"16014218420226057846","ratio":1.0}],"time_taken":0.00028521899366751313},"status":200}
$ sudo service lnx restart # restart lnx
$ curl 'http://localhost:4040/indexes/corrupt/search?query=*&mode=normal&limit=50&order_by=-version'
{"data":{"count":5,"hits":[{"doc":{"field_a":[4],"field_d":[44],"field_f":["foo"]},"document_id":"10440502902603821756","ratio":1.0},{"doc":{"field_a":[5],"field_d":[55],"field_f":["bar"]},"document_id":"17208387925352628110","ratio":1.0},{"doc":{"field_a":[6],"field_d":[66],"field_f":["redbull coke"]},"document_id":"14689755527796750658","ratio":1.0},{"doc":{"field_a":[7],"field_d":[77],"field_f":["vodka sprite"]},"document_id":"16589393346468196154","ratio":1.0},{"doc":{"field_a":[8],"field_d":[88],"field_f":["ginger ale whiskey"]},"document_id":"16014218420226057846","ratio":1.0}],"time_taken":0.00016442099877167493},"status":200}
```

As you can see from the `field_a` is now a `u64` field rather than `text` field and `field_f` is part of the response despite not being a `stored` field.

**Comment by miyachan** [comment] 2021-08-30 03:04
Some futher research shows that `lnx` rebuilds the index from an `IndexDeclaration`:

https://github.com/lnx-search/lnx/blob/476ae66f353f5bb7894aecbed2f12592bbed9c68/engine/src/storage.rs#L36

Which is read from a json file on disk. The fields of this index is then iterated over to recreate the schema

https://github.com/lnx-search/lnx/blob/0d16c7237b382884259b289ed41e27a657f5b6fa/engine/src/structures.rs#L106

I then looked at the json file that is loaded in `storage.rs`

```sh 
$ cat /var/lib/lnx/lnx-data/meta/corrupt  | jq
{
  "name": "corrupt",
  "writer_buffer": 144000000,
  "writer_threads": 1,
  "max_concurrency": 24,
  "reader_threads": 1,
  "search_fields": [
    "field_a"
  ],
  "boost_fields": {},
  "storage_type": "filesystem",
  "fields": {
    "field_d": {
      "type": "text",
      "stored": false
    },
    "version": {
      "type": "u64",
      "indexed": true,
      "fast": "single",
      "stored": false
    },
    "field_b": {
      "type": "u64",
      "indexed": true,
      "fast": "single",
      "stored": true
    },
    "field_c": {
      "type": "u64",
      "indexed": true,
      "fast": "single",
      "stored": true
    },
    "field_a": {
      "type": "text",
      "stored": true
    },
    "field_e": {
      "type": "text",
      "stored": false
    },
    "field_f": {
      "type": "text",
      "stored": false
    }
  },
  "set_conjunction_by_default": true,
  "use_fast_fuzzy": false,
  "strip_stop_words": false
}
```

This file is in a completely different order than what I created - and it is also in a different order than tanvity's `meta.json`:

I'm not sure if guarantees any particular iteration order, so of this process depends on iteration order, this might be why I'm seeing this.

**Comment by miyachan** [comment] 2021-08-30 03:12
I have made a playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=282bdd48d8fce9d1bd7d9f0c09e848fa

In the playground I get this iteration order:

```
Field: field_a
Field: field_e
Field: field_b
Field: version
Field: field_f
Field: field_d
Field: field_c
```

Running it a second time I get:

```
Field: field_f
Field: field_c
Field: field_a
Field: version
Field: field_e
Field: field_b
Field: field_d
```

So if tantivy depends on iteration order to generate field IDs (it does: https://github.com/tantivy-search/tantivy/blob/18377d949c634f056d5a557c88fa11ffe1b43f3f/src/schema/schema.rs#L179), then every time we restart we will get random field IDs.

**Comment by miyachan** [comment] 2021-08-30 03:15
Tantivy's `schema` object uses a custom Deserializer to ensure fields are added to the schema in the same order they are defined:

https://github.com/tantivy-search/tantivy/blob/5b475e6603a66d0e911d2f622e9e79a971dfa7d0/src/schema/schema.rs#L356

**Comment by ChillFish8** [comment] 2021-08-30 09:04
This panic is confusing because Tantivy checks the schema when the index is created and maintains its own definition, this is why this should have rejected the schema as invalid as an error rather than a panic.

Issue wise I think this is actually an issue with how we create the index from a persistent dir, we let tantivy re-create it itself but then keep our older schema as a reference, which I think could cause this issue?

**Comment by ChillFish8** [comment] 2021-08-30 13:01
This wasn't supposed to be closed -_- git branch mix up

**Comment by ChillFish8** [comment] 2021-08-30 13:02
As an extension though I do believe this has been fixed by the changes? If you're able to confirm it would be great as I couldn't directly reproduce this but did notice the discrepencies.

**Comment by miyachan** [comment] 2021-08-30 15:07
I haven't tested it yet, but I think you should remove or fix the parallel schema creation in `IndexDeclaration`. It still represents a potential foot gun that can cause corruption issue due to the undefined iteration order.

**Comment by ChillFish8** [comment] 2021-08-30 15:23
> I haven't tested it yet, but I think you should remove or fix the parallel schema creation in IndexDeclaration. It still represents a potential foot gun that can cause corruption issues due to the undefined iteration order.

It is planned, ideally, I'd like to move away from the JSON file approach and inline it with the SQLite usage.

I think in terms of maintainability the internal API should be re-arranged so that the desync is less likely to happen/be introduced.

**Comment by miyachan** [comment] 2021-08-30 18:38
It looks like the schema is stable now and the PR fixes the issue. I only bring up the `IndexDeclaration` because I don't know what other issues I might hit.

**Comment by ChillFish8** [comment] 2021-08-30 18:43
Yeah, technically the only data that's actually shared between the index declaration and tantivy is the schema. 
Its something that I wonder whether or not to make it so that non-persistent indexes also have non-persistent declarations e.g. restarting the server drops the declaration as well as tantivy's setup.

**Comment by ChillFish8** [comment] 2021-08-30 20:09
Think we can close this now that it seems to have patched it.

**Closed by ChillFish8** 2021-08-30 20:09 UTC
